name: template_flutter
description: Flutter template project with Clean Architecture, Feature-first organization, and flutter_bloc
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Navigation
  go_router: ^14.2.0

  # Localization
  easy_localization: ^3.0.7

  # Network
  dio: ^5.4.1
  connectivity_plus: ^6.0.5

  # Functional Programming (Error Handling)
  dartz: ^0.10.1

  # Local Storage
  shared_preferences: ^2.2.3

  # Notifications
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Refresh Control
  pull_to_refresh: ^2.0.0

  # Utils
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/translations/en.json
    - assets/translations/ru.json

